version: "3.7"

services:

  web:
    image: nginx:1.19.6
    ports:
      - 80:80
    volumes:
      - /home/marco27/dev/repository/git/docker27/nginx/src/v1/www:/var/www/marco27.net
      - /home/marco27/dev/repository/git/docker27/nginx/src/v1/site.conf:/etc/nginx/conf.d/marco27.net.conf